const AuthTypes = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    FORGOT_REQUEST: "FORGOT_REQUEST",
    FORGOT_SUCCESS: "FORGOT_SUCCESS",
    RESET_REQUEST: "RESET_REQUEST",
    RESET_SUCCESS: "RESET_SUCCESS",
    REQUEST_DELETE: "REQUEST_DELETE",
    REQUEST_SUCCESS: "REQUEST_DELETE"

};
export { AuthTypes };
