const HrTypes = {
    HIRING_REQUEST: "HIRING_REQUEST",
    HIRING_SUCCESS: "HIRING_SUCCESS",
    ID_REQUEST: "ID_REQUEST",
    ID_SUCCESS: "ID_SUCCESS",
    ONBOARDING_REQUEST: "ONBOARDING_REQUEST",
    ONBOARDING_SUCCESS: "ONBOARDING_SUCCESS",
    EMPLOYEE_ID_REQUEST: "EMPLOYEE_ID_REQUEST",
    EMPLOYEE_ID_SUCCESS: "EMPLOYEE_ID_SUCCESS",
    TIMESHEET_REQUEST: "TIMESHEET_REQUEST",
    TIMESHEET_SUCCESS: "TIMESHEET_SUCCESS",
    PAYROLL_REQUEST: "PAYROLL_REQUEST",
    PAYROLL_SUCCESS: "PAYROLL_SUCCESS",
};
export { HrTypes };